services:
  php:
    image: php:8.3-cli
    container_name: php83-l8
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:8000"
    command: php -S 0.0.0.0:8000 -t /var/www/html
